version: "3.8"

services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    volumes:
      - ./mongo-test:/data/db
    ports:
      - 27017:27017
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    ports:
      - 5432:5432
